### ISSUE TITLE
Клик по лейблу не выставляет курсор внутри лейбла, а развыделяет лейбл

### ISSUE THREAD

**Issue by yurii-litvinov** [qreal/qreal#1174]
Воспроизводится только с исчезающими лейблами. Кликаем фо блоку, появляется лейбл, дабл-кликаем по нему, он переходит в режим редактирования (при этом как повезёт, либо текст лейбла полностью выделен, либо не выделен и курсор стоит в месте клика). Хотим поставить курсор на определённую позицию внутри лейбла, кликаем по ней --- лейбл выходит из режима редактирования.

**Comment by dvvrd** [comment]
пофикшено
