### ISSUE TITLE
Сегфолт при создании элемента из меню линкера в TRIK Studio

### ISSUE THREAD

**Issue by jzuken** [qreal/qreal#1211]
Создаю новый проект, вытягиваю из элемента "Начало" линкер, выбираю там элемент "Конец", получаю сегфолт. Вот где-то тут:

0	qReal::EdgeElement::setDst	edgeElement.cpp	1072	0x5e8085	
1	qReal::EmbeddedLinker::mouseReleaseEvent	embeddedLinker.cpp	298	0x6127f8	

Watchlist говорит, что там mGraphicalAssistApi null reference.

**Comment by dvvrd** [comment]
Все в порядке
