### ISSUE TITLE
Typo in TRIK Studio

### ISSUE THREAD

**Issue by iakov** [qreal/qreal#1747]
In qrgui/systemFacade/components/autosaver.cpp Line 175 contains a typo: "unusial" should be "unusual".

**Comment by PrikhodkoStanislav** [comment]
Opened pull request with fixes.

**Comment by PrikhodkoStanislav** [comment]
Opened pull request with fixes.

**Comment by PrikhodkoStanislav** [comment]
Opened pull request with fixes.
